language: python
sudo: required
services:
  - docker
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

install:
  - pip install -e .[test,qa] invoke
  - pip install coveralls
before_script:
  - docker-compose up -d
script:
  - inv cover
after_success:
  - coveralls --rcfile=coverage.rc

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
